---
- name: Reboot if required
  reboot:
    msg: "Rebooting the server to apply group changes"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
  become: true
